name: Deploy
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true
        
    - name: Install ImageMagick
      run: |
        sudo apt-get update
        sudo apt-get install -y libmagickwand-dev imagemagick
        
    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          echo "NO_PUSH=--no-push" >> $GITHUB_OUTPUT
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        fi
        echo "DEPLOY_BRANCH=gh-pages" >> $GITHUB_OUTPUT
        
    - name: Deploy website 
      run: |
        # Find the deploy script
        if [ -f bin/deploy ]; then
          DEPLOY_SCRIPT="bin/deploy"
        elif [ -f deploy ]; then
          DEPLOY_SCRIPT="./deploy"
        else
          echo "Deploy script not found!"
          exit 1
        fi
        
        # Make it executable
        chmod +x "$DEPLOY_SCRIPT"
        
        # Run deploy with automatic yes
        echo "y" | "$DEPLOY_SCRIPT" --verbose ${{ steps.setup.outputs.NO_PUSH }} --src ${{ steps.setup.outputs.SRC_BRANCH }} --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
